# Generated by Django 2.0.7 on 2018-07-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=300)),
                ('action', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
    ]
